// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: wallet/v1/wallet.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationWalletServiceGetWallet = "/api.wallet.v1.WalletService/GetWallet"
const OperationWalletServiceListLedger = "/api.wallet.v1.WalletService/ListLedger"
const OperationWalletServiceRecharge = "/api.wallet.v1.WalletService/Recharge"

type WalletServiceHTTPServer interface {
	GetWallet(context.Context, *GetWalletRequest) (*GetWalletReply, error)
	ListLedger(context.Context, *ListLedgerRequest) (*ListLedgerReply, error)
	Recharge(context.Context, *RechargeRequest) (*RechargeReply, error)
}

func RegisterWalletServiceHTTPServer(s *http.Server, srv WalletServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/wallet", _WalletService_GetWallet0_HTTP_Handler(srv))
	r.POST("/v1/wallet/recharge", _WalletService_Recharge0_HTTP_Handler(srv))
	r.GET("/v1/wallet/ledger", _WalletService_ListLedger0_HTTP_Handler(srv))
}

func _WalletService_GetWallet0_HTTP_Handler(srv WalletServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWalletRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWalletServiceGetWallet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWallet(ctx, req.(*GetWalletRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetWalletReply)
		return ctx.Result(200, reply)
	}
}

func _WalletService_Recharge0_HTTP_Handler(srv WalletServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RechargeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWalletServiceRecharge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Recharge(ctx, req.(*RechargeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RechargeReply)
		return ctx.Result(200, reply)
	}
}

func _WalletService_ListLedger0_HTTP_Handler(srv WalletServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLedgerRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWalletServiceListLedger)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLedger(ctx, req.(*ListLedgerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLedgerReply)
		return ctx.Result(200, reply)
	}
}

type WalletServiceHTTPClient interface {
	GetWallet(ctx context.Context, req *GetWalletRequest, opts ...http.CallOption) (rsp *GetWalletReply, err error)
	ListLedger(ctx context.Context, req *ListLedgerRequest, opts ...http.CallOption) (rsp *ListLedgerReply, err error)
	Recharge(ctx context.Context, req *RechargeRequest, opts ...http.CallOption) (rsp *RechargeReply, err error)
}

type WalletServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewWalletServiceHTTPClient(client *http.Client) WalletServiceHTTPClient {
	return &WalletServiceHTTPClientImpl{client}
}

func (c *WalletServiceHTTPClientImpl) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...http.CallOption) (*GetWalletReply, error) {
	var out GetWalletReply
	pattern := "/v1/wallet"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWalletServiceGetWallet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WalletServiceHTTPClientImpl) ListLedger(ctx context.Context, in *ListLedgerRequest, opts ...http.CallOption) (*ListLedgerReply, error) {
	var out ListLedgerReply
	pattern := "/v1/wallet/ledger"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWalletServiceListLedger))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WalletServiceHTTPClientImpl) Recharge(ctx context.Context, in *RechargeRequest, opts ...http.CallOption) (*RechargeReply, error) {
	var out RechargeReply
	pattern := "/v1/wallet/recharge"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWalletServiceRecharge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
