// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: wallet/v1/wallet.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{0}
}

type GetWalletReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BalanceFen    int64                  `protobuf:"varint,1,opt,name=balance_fen,json=balanceFen,proto3" json:"balance_fen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletReply) Reset() {
	*x = GetWalletReply{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletReply) ProtoMessage() {}

func (x *GetWalletReply) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletReply.ProtoReflect.Descriptor instead.
func (*GetWalletReply) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *GetWalletReply) GetBalanceFen() int64 {
	if x != nil {
		return x.BalanceFen
	}
	return 0
}

type RechargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountFen     int64                  `protobuf:"varint,1,opt,name=amount_fen,json=amountFen,proto3" json:"amount_fen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeRequest) Reset() {
	*x = RechargeRequest{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeRequest) ProtoMessage() {}

func (x *RechargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeRequest.ProtoReflect.Descriptor instead.
func (*RechargeRequest) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *RechargeRequest) GetAmountFen() int64 {
	if x != nil {
		return x.AmountFen
	}
	return 0
}

type RechargeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BalanceFen    int64                  `protobuf:"varint,1,opt,name=balance_fen,json=balanceFen,proto3" json:"balance_fen,omitempty"`
	Entry         *LedgerEntry           `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeReply) Reset() {
	*x = RechargeReply{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeReply) ProtoMessage() {}

func (x *RechargeReply) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeReply.ProtoReflect.Descriptor instead.
func (*RechargeReply) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *RechargeReply) GetBalanceFen() int64 {
	if x != nil {
		return x.BalanceFen
	}
	return 0
}

func (x *RechargeReply) GetEntry() *LedgerEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type ListLedgerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerRequest) Reset() {
	*x = ListLedgerRequest{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerRequest) ProtoMessage() {}

func (x *ListLedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerRequest.ProtoReflect.Descriptor instead.
func (*ListLedgerRequest) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *ListLedgerRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLedgerRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListLedgerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LedgerEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerReply) Reset() {
	*x = ListLedgerReply{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerReply) ProtoMessage() {}

func (x *ListLedgerReply) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerReply.ProtoReflect.Descriptor instead.
func (*ListLedgerReply) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *ListLedgerReply) GetEntries() []*LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListLedgerReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type LedgerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AmountFen     int64                  `protobuf:"varint,2,opt,name=amount_fen,json=amountFen,proto3" json:"amount_fen,omitempty"`
	BalanceFen    int64                  `protobuf:"varint,3,opt,name=balance_fen,json=balanceFen,proto3" json:"balance_fen,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	RefType       string                 `protobuf:"bytes,5,opt,name=ref_type,json=refType,proto3" json:"ref_type,omitempty"`
	RefId         int64                  `protobuf:"varint,6,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *LedgerEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LedgerEntry) GetAmountFen() int64 {
	if x != nil {
		return x.AmountFen
	}
	return 0
}

func (x *LedgerEntry) GetBalanceFen() int64 {
	if x != nil {
		return x.BalanceFen
	}
	return 0
}

func (x *LedgerEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LedgerEntry) GetRefType() string {
	if x != nil {
		return x.RefType
	}
	return ""
}

func (x *LedgerEntry) GetRefId() int64 {
	if x != nil {
		return x.RefId
	}
	return 0
}

func (x *LedgerEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_wallet_v1_wallet_proto protoreflect.FileDescriptor

const file_wallet_v1_wallet_proto_rawDesc = "" +
	"\n" +
	"\x16wallet/v1/wallet.proto\x12\rapi.wallet.v1\x1a\x1cgoogle/api/annotations.proto\"\x12\n" +
	"\x10GetWalletRequest\"1\n" +
	"\x0eGetWalletReply\x12\x1f\n" +
	"\vbalance_fen\x18\x01 \x01(\x03R\n" +
	"balanceFen\"0\n" +
	"\x0fRechargeRequest\x12\x1d\n" +
	"\n" +
	"amount_fen\x18\x01 \x01(\x03R\tamountFen\"b\n" +
	"\rRechargeReply\x12\x1f\n" +
	"\vbalance_fen\x18\x01 \x01(\x03R\n" +
	"balanceFen\x120\n" +
	"\x05entry\x18\x02 \x01(\v2\x1a.api.wallet.v1.LedgerEntryR\x05entry\"D\n" +
	"\x11ListLedgerRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"]\n" +
	"\x0fListLedgerReply\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.api.wallet.v1.LedgerEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xc2\x01\n" +
	"\vLedgerEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"amount_fen\x18\x02 \x01(\x03R\tamountFen\x12\x1f\n" +
	"\vbalance_fen\x18\x03 \x01(\x03R\n" +
	"balanceFen\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x19\n" +
	"\bref_type\x18\x05 \x01(\tR\arefType\x12\x15\n" +
	"\x06ref_id\x18\x06 \x01(\x03R\x05refId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt2\xc5\x02\n" +
	"\rWalletService\x12_\n" +
	"\tGetWallet\x12\x1f.api.wallet.v1.GetWalletRequest\x1a\x1d.api.wallet.v1.GetWalletReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/wallet\x12h\n" +
	"\bRecharge\x12\x1e.api.wallet.v1.RechargeRequest\x1a\x1c.api.wallet.v1.RechargeReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/wallet/recharge\x12i\n" +
	"\n" +
	"ListLedger\x12 .api.wallet.v1.ListLedgerRequest\x1a\x1e.api.wallet.v1.ListLedgerReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/wallet/ledgerB\x17Z\x15mall/api/wallet/v1;v1b\x06proto3"

var (
	file_wallet_v1_wallet_proto_rawDescOnce sync.Once
	file_wallet_v1_wallet_proto_rawDescData []byte
)

func file_wallet_v1_wallet_proto_rawDescGZIP() []byte {
	file_wallet_v1_wallet_proto_rawDescOnce.Do(func() {
		file_wallet_v1_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_v1_wallet_proto_rawDesc), len(file_wallet_v1_wallet_proto_rawDesc)))
	})
	return file_wallet_v1_wallet_proto_rawDescData
}

var file_wallet_v1_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_wallet_v1_wallet_proto_goTypes = []any{
	(*GetWalletRequest)(nil),  // 0: api.wallet.v1.GetWalletRequest
	(*GetWalletReply)(nil),    // 1: api.wallet.v1.GetWalletReply
	(*RechargeRequest)(nil),   // 2: api.wallet.v1.RechargeRequest
	(*RechargeReply)(nil),     // 3: api.wallet.v1.RechargeReply
	(*ListLedgerRequest)(nil), // 4: api.wallet.v1.ListLedgerRequest
	(*ListLedgerReply)(nil),   // 5: api.wallet.v1.ListLedgerReply
	(*LedgerEntry)(nil),       // 6: api.wallet.v1.LedgerEntry
}
var file_wallet_v1_wallet_proto_depIdxs = []int32{
	6, // 0: api.wallet.v1.RechargeReply.entry:type_name -> api.wallet.v1.LedgerEntry
	6, // 1: api.wallet.v1.ListLedgerReply.entries:type_name -> api.wallet.v1.LedgerEntry
	0, // 2: api.wallet.v1.WalletService.GetWallet:input_type -> api.wallet.v1.GetWalletRequest
	2, // 3: api.wallet.v1.WalletService.Recharge:input_type -> api.wallet.v1.RechargeRequest
	4, // 4: api.wallet.v1.WalletService.ListLedger:input_type -> api.wallet.v1.ListLedgerRequest
	1, // 5: api.wallet.v1.WalletService.GetWallet:output_type -> api.wallet.v1.GetWalletReply
	3, // 6: api.wallet.v1.WalletService.Recharge:output_type -> api.wallet.v1.RechargeReply
	5, // 7: api.wallet.v1.WalletService.ListLedger:output_type -> api.wallet.v1.ListLedgerReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wallet_v1_wallet_proto_init() }
func file_wallet_v1_wallet_proto_init() {
	if File_wallet_v1_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_v1_wallet_proto_rawDesc), len(file_wallet_v1_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_v1_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_v1_wallet_proto_depIdxs,
		MessageInfos:      file_wallet_v1_wallet_proto_msgTypes,
	}.Build()
	File_wallet_v1_wallet_proto = out.File
	file_wallet_v1_wallet_proto_goTypes = nil
	file_wallet_v1_wallet_proto_depIdxs = nil
}
