// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: user/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNonceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNonceRequest) Reset() {
	*x = GetNonceRequest{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNonceRequest) ProtoMessage() {}

func (x *GetNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNonceRequest.ProtoReflect.Descriptor instead.
func (*GetNonceRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetNonceRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type GetNonceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNonceReply) Reset() {
	*x = GetNonceReply{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNonceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNonceReply) ProtoMessage() {}

func (x *GetNonceReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNonceReply.ProtoReflect.Descriptor instead.
func (*GetNonceReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetNonceReply) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type WalletLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	InviteCode    string                 `protobuf:"bytes,3,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletLoginRequest) Reset() {
	*x = WalletLoginRequest{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletLoginRequest) ProtoMessage() {}

func (x *WalletLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletLoginRequest.ProtoReflect.Descriptor instead.
func (*WalletLoginRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *WalletLoginRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WalletLoginRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *WalletLoginRequest) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

type WalletLoginReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Token           string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	WalletAddress   string                 `protobuf:"bytes,3,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Nickname        string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar          string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	InviteCode      string                 `protobuf:"bytes,6,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	InviterId       int64                  `protobuf:"varint,7,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	InviterNickname string                 `protobuf:"bytes,8,opt,name=inviter_nickname,json=inviterNickname,proto3" json:"inviter_nickname,omitempty"`
	ParentId        int64                  `protobuf:"varint,9,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Side            string                 `protobuf:"bytes,10,opt,name=side,proto3" json:"side,omitempty"`
	IsAdmin         bool                   `protobuf:"varint,11,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WalletLoginReply) Reset() {
	*x = WalletLoginReply{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletLoginReply) ProtoMessage() {}

func (x *WalletLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletLoginReply.ProtoReflect.Descriptor instead.
func (*WalletLoginReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *WalletLoginReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WalletLoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WalletLoginReply) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *WalletLoginReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *WalletLoginReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *WalletLoginReply) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *WalletLoginReply) GetInviterId() int64 {
	if x != nil {
		return x.InviterId
	}
	return 0
}

func (x *WalletLoginReply) GetInviterNickname() string {
	if x != nil {
		return x.InviterNickname
	}
	return ""
}

func (x *WalletLoginReply) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *WalletLoginReply) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *WalletLoginReply) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

type GetMeReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletAddress   string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Nickname        string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar          string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	InviteCode      string                 `protobuf:"bytes,5,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	InviterId       int64                  `protobuf:"varint,6,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	InviterNickname string                 `protobuf:"bytes,7,opt,name=inviter_nickname,json=inviterNickname,proto3" json:"inviter_nickname,omitempty"`
	ParentId        int64                  `protobuf:"varint,8,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Side            string                 `protobuf:"bytes,9,opt,name=side,proto3" json:"side,omitempty"`
	IsAdmin         bool                   `protobuf:"varint,10,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMeReply) Reset() {
	*x = GetMeReply{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeReply) ProtoMessage() {}

func (x *GetMeReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeReply.ProtoReflect.Descriptor instead.
func (*GetMeReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetMeReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMeReply) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *GetMeReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetMeReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetMeReply) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *GetMeReply) GetInviterId() int64 {
	if x != nil {
		return x.InviterId
	}
	return 0
}

func (x *GetMeReply) GetInviterNickname() string {
	if x != nil {
		return x.InviterNickname
	}
	return ""
}

func (x *GetMeReply) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *GetMeReply) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *GetMeReply) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type UpdateMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeRequest) Reset() {
	*x = UpdateMeRequest{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeRequest) ProtoMessage() {}

func (x *UpdateMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeRequest.ProtoReflect.Descriptor instead.
func (*UpdateMeRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMeRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateMeRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

type GetInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInviteRequest) Reset() {
	*x = GetInviteRequest{}
	mi := &file_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteRequest) ProtoMessage() {}

func (x *GetInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteRequest.ProtoReflect.Descriptor instead.
func (*GetInviteRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{9}
}

type InviteMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	InviteCode    string                 `protobuf:"bytes,3,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	Side          string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	PerfFen       int64                  `protobuf:"varint,5,opt,name=perf_fen,json=perfFen,proto3" json:"perf_fen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMember) Reset() {
	*x = InviteMember{}
	mi := &file_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMember) ProtoMessage() {}

func (x *InviteMember) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMember.ProtoReflect.Descriptor instead.
func (*InviteMember) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *InviteMember) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InviteMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *InviteMember) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *InviteMember) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *InviteMember) GetPerfFen() int64 {
	if x != nil {
		return x.PerfFen
	}
	return 0
}

type GetInviteReply struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InviteCode          string                 `protobuf:"bytes,1,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	InviterId           int64                  `protobuf:"varint,2,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	InviterNickname     string                 `protobuf:"bytes,3,opt,name=inviter_nickname,json=inviterNickname,proto3" json:"inviter_nickname,omitempty"`
	ParentId            int64                  `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Side                string                 `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"`
	LeftCount           int64                  `protobuf:"varint,6,opt,name=left_count,json=leftCount,proto3" json:"left_count,omitempty"`
	RightCount          int64                  `protobuf:"varint,7,opt,name=right_count,json=rightCount,proto3" json:"right_count,omitempty"`
	LeftMembers         []*InviteMember        `protobuf:"bytes,8,rep,name=left_members,json=leftMembers,proto3" json:"left_members,omitempty"`
	RightMembers        []*InviteMember        `protobuf:"bytes,9,rep,name=right_members,json=rightMembers,proto3" json:"right_members,omitempty"`
	Invitees            []*InviteMember        `protobuf:"bytes,10,rep,name=invitees,proto3" json:"invitees,omitempty"`
	LeftPerfFen         int64                  `protobuf:"varint,11,opt,name=left_perf_fen,json=leftPerfFen,proto3" json:"left_perf_fen,omitempty"`
	RightPerfFen        int64                  `protobuf:"varint,12,opt,name=right_perf_fen,json=rightPerfFen,proto3" json:"right_perf_fen,omitempty"`
	SettledPairFen      int64                  `protobuf:"varint,13,opt,name=settled_pair_fen,json=settledPairFen,proto3" json:"settled_pair_fen,omitempty"`
	PairClearedRightFen int64                  `protobuf:"varint,14,opt,name=pair_cleared_right_fen,json=pairClearedRightFen,proto3" json:"pair_cleared_right_fen,omitempty"`
	AvailLeftFen        int64                  `protobuf:"varint,15,opt,name=avail_left_fen,json=availLeftFen,proto3" json:"avail_left_fen,omitempty"`
	AvailRightFen       int64                  `protobuf:"varint,16,opt,name=avail_right_fen,json=availRightFen,proto3" json:"avail_right_fen,omitempty"`
	PairVolFen          int64                  `protobuf:"varint,17,opt,name=pair_vol_fen,json=pairVolFen,proto3" json:"pair_vol_fen,omitempty"`
	PairCapFen          int64                  `protobuf:"varint,18,opt,name=pair_cap_fen,json=pairCapFen,proto3" json:"pair_cap_fen,omitempty"`
	EstPairPayFen       int64                  `protobuf:"varint,19,opt,name=est_pair_pay_fen,json=estPairPayFen,proto3" json:"est_pair_pay_fen,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetInviteReply) Reset() {
	*x = GetInviteReply{}
	mi := &file_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteReply) ProtoMessage() {}

func (x *GetInviteReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteReply.ProtoReflect.Descriptor instead.
func (*GetInviteReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetInviteReply) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *GetInviteReply) GetInviterId() int64 {
	if x != nil {
		return x.InviterId
	}
	return 0
}

func (x *GetInviteReply) GetInviterNickname() string {
	if x != nil {
		return x.InviterNickname
	}
	return ""
}

func (x *GetInviteReply) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *GetInviteReply) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *GetInviteReply) GetLeftCount() int64 {
	if x != nil {
		return x.LeftCount
	}
	return 0
}

func (x *GetInviteReply) GetRightCount() int64 {
	if x != nil {
		return x.RightCount
	}
	return 0
}

func (x *GetInviteReply) GetLeftMembers() []*InviteMember {
	if x != nil {
		return x.LeftMembers
	}
	return nil
}

func (x *GetInviteReply) GetRightMembers() []*InviteMember {
	if x != nil {
		return x.RightMembers
	}
	return nil
}

func (x *GetInviteReply) GetInvitees() []*InviteMember {
	if x != nil {
		return x.Invitees
	}
	return nil
}

func (x *GetInviteReply) GetLeftPerfFen() int64 {
	if x != nil {
		return x.LeftPerfFen
	}
	return 0
}

func (x *GetInviteReply) GetRightPerfFen() int64 {
	if x != nil {
		return x.RightPerfFen
	}
	return 0
}

func (x *GetInviteReply) GetSettledPairFen() int64 {
	if x != nil {
		return x.SettledPairFen
	}
	return 0
}

func (x *GetInviteReply) GetPairClearedRightFen() int64 {
	if x != nil {
		return x.PairClearedRightFen
	}
	return 0
}

func (x *GetInviteReply) GetAvailLeftFen() int64 {
	if x != nil {
		return x.AvailLeftFen
	}
	return 0
}

func (x *GetInviteReply) GetAvailRightFen() int64 {
	if x != nil {
		return x.AvailRightFen
	}
	return 0
}

func (x *GetInviteReply) GetPairVolFen() int64 {
	if x != nil {
		return x.PairVolFen
	}
	return 0
}

func (x *GetInviteReply) GetPairCapFen() int64 {
	if x != nil {
		return x.PairCapFen
	}
	return 0
}

func (x *GetInviteReply) GetEstPairPayFen() int64 {
	if x != nil {
		return x.EstPairPayFen
	}
	return 0
}

type BindInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteCode    string                 `protobuf:"bytes,1,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindInviteRequest) Reset() {
	*x = BindInviteRequest{}
	mi := &file_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindInviteRequest) ProtoMessage() {}

func (x *BindInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindInviteRequest.ProtoReflect.Descriptor instead.
func (*BindInviteRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *BindInviteRequest) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\vapi.user.v1\x1a\x1cgoogle/api/annotations.proto\"8\n" +
	"\x0fGetNonceRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\"%\n" +
	"\rGetNonceReply\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\"m\n" +
	"\x12WalletLoginRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x1f\n" +
	"\vinvite_code\x18\x03 \x01(\tR\n" +
	"inviteCode\"\xca\x02\n" +
	"\x10WalletLoginReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12%\n" +
	"\x0ewallet_address\x18\x03 \x01(\tR\rwalletAddress\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x1f\n" +
	"\vinvite_code\x18\x06 \x01(\tR\n" +
	"inviteCode\x12\x1d\n" +
	"\n" +
	"inviter_id\x18\a \x01(\x03R\tinviterId\x12)\n" +
	"\x10inviter_nickname\x18\b \x01(\tR\x0finviterNickname\x12\x1b\n" +
	"\tparent_id\x18\t \x01(\x03R\bparentId\x12\x12\n" +
	"\x04side\x18\n" +
	" \x01(\tR\x04side\x12\x19\n" +
	"\bis_admin\x18\v \x01(\bR\aisAdmin\"\x0e\n" +
	"\fGetMeRequest\"\xae\x02\n" +
	"\n" +
	"GetMeReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x1f\n" +
	"\vinvite_code\x18\x05 \x01(\tR\n" +
	"inviteCode\x12\x1d\n" +
	"\n" +
	"inviter_id\x18\x06 \x01(\x03R\tinviterId\x12)\n" +
	"\x10inviter_nickname\x18\a \x01(\tR\x0finviterNickname\x12\x1b\n" +
	"\tparent_id\x18\b \x01(\x03R\bparentId\x12\x12\n" +
	"\x04side\x18\t \x01(\tR\x04side\x12\x19\n" +
	"\bis_admin\x18\n" +
	" \x01(\bR\aisAdmin\"E\n" +
	"\x0fUpdateMeRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\"\x0f\n" +
	"\rLogoutRequest\"\r\n" +
	"\vLogoutReply\"\x12\n" +
	"\x10GetInviteRequest\"\x8a\x01\n" +
	"\fInviteMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1f\n" +
	"\vinvite_code\x18\x03 \x01(\tR\n" +
	"inviteCode\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12\x19\n" +
	"\bperf_fen\x18\x05 \x01(\x03R\aperfFen\"\x85\x06\n" +
	"\x0eGetInviteReply\x12\x1f\n" +
	"\vinvite_code\x18\x01 \x01(\tR\n" +
	"inviteCode\x12\x1d\n" +
	"\n" +
	"inviter_id\x18\x02 \x01(\x03R\tinviterId\x12)\n" +
	"\x10inviter_nickname\x18\x03 \x01(\tR\x0finviterNickname\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04side\x18\x05 \x01(\tR\x04side\x12\x1d\n" +
	"\n" +
	"left_count\x18\x06 \x01(\x03R\tleftCount\x12\x1f\n" +
	"\vright_count\x18\a \x01(\x03R\n" +
	"rightCount\x12<\n" +
	"\fleft_members\x18\b \x03(\v2\x19.api.user.v1.InviteMemberR\vleftMembers\x12>\n" +
	"\rright_members\x18\t \x03(\v2\x19.api.user.v1.InviteMemberR\frightMembers\x125\n" +
	"\binvitees\x18\n" +
	" \x03(\v2\x19.api.user.v1.InviteMemberR\binvitees\x12\"\n" +
	"\rleft_perf_fen\x18\v \x01(\x03R\vleftPerfFen\x12$\n" +
	"\x0eright_perf_fen\x18\f \x01(\x03R\frightPerfFen\x12(\n" +
	"\x10settled_pair_fen\x18\r \x01(\x03R\x0esettledPairFen\x123\n" +
	"\x16pair_cleared_right_fen\x18\x0e \x01(\x03R\x13pairClearedRightFen\x12$\n" +
	"\x0eavail_left_fen\x18\x0f \x01(\x03R\favailLeftFen\x12&\n" +
	"\x0favail_right_fen\x18\x10 \x01(\x03R\ravailRightFen\x12 \n" +
	"\fpair_vol_fen\x18\x11 \x01(\x03R\n" +
	"pairVolFen\x12 \n" +
	"\fpair_cap_fen\x18\x12 \x01(\x03R\n" +
	"pairCapFen\x12'\n" +
	"\x10est_pair_pay_fen\x18\x13 \x01(\x03R\restPairPayFen\"4\n" +
	"\x11BindInviteRequest\x12\x1f\n" +
	"\vinvite_code\x18\x01 \x01(\tR\n" +
	"inviteCode2\xad\x05\n" +
	"\vUserService\x12`\n" +
	"\bGetNonce\x12\x1c.api.user.v1.GetNonceRequest\x1a\x1a.api.user.v1.GetNonceReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/users/nonce\x12p\n" +
	"\vWalletLogin\x12\x1f.api.user.v1.WalletLoginRequest\x1a\x1d.api.user.v1.WalletLoginReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/users/wallet-login\x12Q\n" +
	"\x05GetMe\x12\x19.api.user.v1.GetMeRequest\x1a\x17.api.user.v1.GetMeReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/users/me\x12Z\n" +
	"\bUpdateMe\x12\x1c.api.user.v1.UpdateMeRequest\x1a\x17.api.user.v1.GetMeReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\x1a\f/v1/users/me\x12[\n" +
	"\x06Logout\x12\x1a.api.user.v1.LogoutRequest\x1a\x18.api.user.v1.LogoutReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/users/logout\x12[\n" +
	"\tGetInvite\x12\x1d.api.user.v1.GetInviteRequest\x1a\x1b.api.user.v1.GetInviteReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/invite\x12a\n" +
	"\n" +
	"BindInvite\x12\x1e.api.user.v1.BindInviteRequest\x1a\x17.api.user.v1.GetMeReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/invite/bindB\x15Z\x13mall/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_user_v1_user_proto_goTypes = []any{
	(*GetNonceRequest)(nil),    // 0: api.user.v1.GetNonceRequest
	(*GetNonceReply)(nil),      // 1: api.user.v1.GetNonceReply
	(*WalletLoginRequest)(nil), // 2: api.user.v1.WalletLoginRequest
	(*WalletLoginReply)(nil),   // 3: api.user.v1.WalletLoginReply
	(*GetMeRequest)(nil),       // 4: api.user.v1.GetMeRequest
	(*GetMeReply)(nil),         // 5: api.user.v1.GetMeReply
	(*UpdateMeRequest)(nil),    // 6: api.user.v1.UpdateMeRequest
	(*LogoutRequest)(nil),      // 7: api.user.v1.LogoutRequest
	(*LogoutReply)(nil),        // 8: api.user.v1.LogoutReply
	(*GetInviteRequest)(nil),   // 9: api.user.v1.GetInviteRequest
	(*InviteMember)(nil),       // 10: api.user.v1.InviteMember
	(*GetInviteReply)(nil),     // 11: api.user.v1.GetInviteReply
	(*BindInviteRequest)(nil),  // 12: api.user.v1.BindInviteRequest
}
var file_user_v1_user_proto_depIdxs = []int32{
	10, // 0: api.user.v1.GetInviteReply.left_members:type_name -> api.user.v1.InviteMember
	10, // 1: api.user.v1.GetInviteReply.right_members:type_name -> api.user.v1.InviteMember
	10, // 2: api.user.v1.GetInviteReply.invitees:type_name -> api.user.v1.InviteMember
	0,  // 3: api.user.v1.UserService.GetNonce:input_type -> api.user.v1.GetNonceRequest
	2,  // 4: api.user.v1.UserService.WalletLogin:input_type -> api.user.v1.WalletLoginRequest
	4,  // 5: api.user.v1.UserService.GetMe:input_type -> api.user.v1.GetMeRequest
	6,  // 6: api.user.v1.UserService.UpdateMe:input_type -> api.user.v1.UpdateMeRequest
	7,  // 7: api.user.v1.UserService.Logout:input_type -> api.user.v1.LogoutRequest
	9,  // 8: api.user.v1.UserService.GetInvite:input_type -> api.user.v1.GetInviteRequest
	12, // 9: api.user.v1.UserService.BindInvite:input_type -> api.user.v1.BindInviteRequest
	1,  // 10: api.user.v1.UserService.GetNonce:output_type -> api.user.v1.GetNonceReply
	3,  // 11: api.user.v1.UserService.WalletLogin:output_type -> api.user.v1.WalletLoginReply
	5,  // 12: api.user.v1.UserService.GetMe:output_type -> api.user.v1.GetMeReply
	5,  // 13: api.user.v1.UserService.UpdateMe:output_type -> api.user.v1.GetMeReply
	8,  // 14: api.user.v1.UserService.Logout:output_type -> api.user.v1.LogoutReply
	11, // 15: api.user.v1.UserService.GetInvite:output_type -> api.user.v1.GetInviteReply
	5,  // 16: api.user.v1.UserService.BindInvite:output_type -> api.user.v1.GetMeReply
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
