// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"mall/internal/biz"
	"mall/internal/conf"
	"mall/internal/data"
	"mall/internal/server"
	"mall/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	userRepo := data.NewUserRepo(dataData)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase)
	productRepo := data.NewProductRepo(dataData)
	productUsecase := biz.NewProductUsecase(productRepo, logger)
	productService := service.NewProductService(productUsecase)
	shopRepo := data.NewShopRepo(dataData)
	walletUsecase := biz.NewWalletUsecase(shopRepo, userUsecase, logger)
	walletService := service.NewWalletService(walletUsecase)
	orderUsecase := biz.NewOrderUsecase(shopRepo, userUsecase, logger)
	orderService := service.NewOrderService(orderUsecase)
	adminUsecase := biz.NewAdminUsecase(data.NewAdminRepo(dataData), userUsecase, userRepo, logger)
	adminService := service.NewAdminService(adminUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, userService, productService, walletService, orderService, adminService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, userService, productService, walletService, orderService, adminService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
