// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: admin/v1/admin.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

type GetStatsReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserCount          int64                  `protobuf:"varint,1,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	PaidOrderFen       int64                  `protobuf:"varint,2,opt,name=paid_order_fen,json=paidOrderFen,proto3" json:"paid_order_fen,omitempty"`
	DirectRewardFen    int64                  `protobuf:"varint,3,opt,name=direct_reward_fen,json=directRewardFen,proto3" json:"direct_reward_fen,omitempty"`
	PairRewardFen      int64                  `protobuf:"varint,4,opt,name=pair_reward_fen,json=pairRewardFen,proto3" json:"pair_reward_fen,omitempty"`
	ManageRewardFen    int64                  `protobuf:"varint,5,opt,name=manage_reward_fen,json=manageRewardFen,proto3" json:"manage_reward_fen,omitempty"`
	LastPairSettleDate string                 `protobuf:"bytes,6,opt,name=last_pair_settle_date,json=lastPairSettleDate,proto3" json:"last_pair_settle_date,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStatsReply) Reset() {
	*x = GetStatsReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsReply) ProtoMessage() {}

func (x *GetStatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsReply.ProtoReflect.Descriptor instead.
func (*GetStatsReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatsReply) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *GetStatsReply) GetPaidOrderFen() int64 {
	if x != nil {
		return x.PaidOrderFen
	}
	return 0
}

func (x *GetStatsReply) GetDirectRewardFen() int64 {
	if x != nil {
		return x.DirectRewardFen
	}
	return 0
}

func (x *GetStatsReply) GetPairRewardFen() int64 {
	if x != nil {
		return x.PairRewardFen
	}
	return 0
}

func (x *GetStatsReply) GetManageRewardFen() int64 {
	if x != nil {
		return x.ManageRewardFen
	}
	return 0
}

func (x *GetStatsReply) GetLastPairSettleDate() string {
	if x != nil {
		return x.LastPairSettleDate
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AdminUser struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletAddress  string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Nickname       string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	InviteCode     string                 `protobuf:"bytes,4,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	InviterId      int64                  `protobuf:"varint,5,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	ParentId       int64                  `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Side           string                 `protobuf:"bytes,7,opt,name=side,proto3" json:"side,omitempty"`
	PerfFen        int64                  `protobuf:"varint,8,opt,name=perf_fen,json=perfFen,proto3" json:"perf_fen,omitempty"`
	SettledPairFen int64                  `protobuf:"varint,9,opt,name=settled_pair_fen,json=settledPairFen,proto3" json:"settled_pair_fen,omitempty"`
	BalanceFen     int64                  `protobuf:"varint,10,opt,name=balance_fen,json=balanceFen,proto3" json:"balance_fen,omitempty"`
	IsAdmin        bool                   `protobuf:"varint,11,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUser) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *AdminUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AdminUser) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *AdminUser) GetInviterId() int64 {
	if x != nil {
		return x.InviterId
	}
	return 0
}

func (x *AdminUser) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *AdminUser) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *AdminUser) GetPerfFen() int64 {
	if x != nil {
		return x.PerfFen
	}
	return 0
}

func (x *AdminUser) GetSettledPairFen() int64 {
	if x != nil {
		return x.SettledPairFen
	}
	return 0
}

func (x *AdminUser) GetBalanceFen() int64 {
	if x != nil {
		return x.BalanceFen
	}
	return 0
}

func (x *AdminUser) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type ListUsersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*AdminUser           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersReply) Reset() {
	*x = ListUsersReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersReply) ProtoMessage() {}

func (x *ListUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersReply.ProtoReflect.Descriptor instead.
func (*ListUsersReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersReply) GetUsers() []*AdminUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TrackMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	InviteCode    string                 `protobuf:"bytes,3,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	PerfFen       int64                  `protobuf:"varint,4,opt,name=perf_fen,json=perfFen,proto3" json:"perf_fen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackMember) Reset() {
	*x = TrackMember{}
	mi := &file_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackMember) ProtoMessage() {}

func (x *TrackMember) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackMember.ProtoReflect.Descriptor instead.
func (*TrackMember) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *TrackMember) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TrackMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *TrackMember) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *TrackMember) GetPerfFen() int64 {
	if x != nil {
		return x.PerfFen
	}
	return 0
}

type GetUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *AdminUser             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	LeftPerfFen   int64                  `protobuf:"varint,2,opt,name=left_perf_fen,json=leftPerfFen,proto3" json:"left_perf_fen,omitempty"`
	RightPerfFen  int64                  `protobuf:"varint,3,opt,name=right_perf_fen,json=rightPerfFen,proto3" json:"right_perf_fen,omitempty"`
	AvailLeftFen  int64                  `protobuf:"varint,4,opt,name=avail_left_fen,json=availLeftFen,proto3" json:"avail_left_fen,omitempty"`
	AvailRightFen int64                  `protobuf:"varint,5,opt,name=avail_right_fen,json=availRightFen,proto3" json:"avail_right_fen,omitempty"`
	PairVolFen    int64                  `protobuf:"varint,6,opt,name=pair_vol_fen,json=pairVolFen,proto3" json:"pair_vol_fen,omitempty"`
	PairCapFen    int64                  `protobuf:"varint,7,opt,name=pair_cap_fen,json=pairCapFen,proto3" json:"pair_cap_fen,omitempty"`
	EstPairPayFen int64                  `protobuf:"varint,8,opt,name=est_pair_pay_fen,json=estPairPayFen,proto3" json:"est_pair_pay_fen,omitempty"`
	LeftMembers   []*TrackMember         `protobuf:"bytes,9,rep,name=left_members,json=leftMembers,proto3" json:"left_members,omitempty"`
	RightMembers  []*TrackMember         `protobuf:"bytes,10,rep,name=right_members,json=rightMembers,proto3" json:"right_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReply) Reset() {
	*x = GetUserReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReply) ProtoMessage() {}

func (x *GetUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReply.ProtoReflect.Descriptor instead.
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserReply) GetUser() *AdminUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserReply) GetLeftPerfFen() int64 {
	if x != nil {
		return x.LeftPerfFen
	}
	return 0
}

func (x *GetUserReply) GetRightPerfFen() int64 {
	if x != nil {
		return x.RightPerfFen
	}
	return 0
}

func (x *GetUserReply) GetAvailLeftFen() int64 {
	if x != nil {
		return x.AvailLeftFen
	}
	return 0
}

func (x *GetUserReply) GetAvailRightFen() int64 {
	if x != nil {
		return x.AvailRightFen
	}
	return 0
}

func (x *GetUserReply) GetPairVolFen() int64 {
	if x != nil {
		return x.PairVolFen
	}
	return 0
}

func (x *GetUserReply) GetPairCapFen() int64 {
	if x != nil {
		return x.PairCapFen
	}
	return 0
}

func (x *GetUserReply) GetEstPairPayFen() int64 {
	if x != nil {
		return x.EstPairPayFen
	}
	return 0
}

func (x *GetUserReply) GetLeftMembers() []*TrackMember {
	if x != nil {
		return x.LeftMembers
	}
	return nil
}

func (x *GetUserReply) GetRightMembers() []*TrackMember {
	if x != nil {
		return x.RightMembers
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

type AdminProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PriceFen      int64                  `protobuf:"varint,3,opt,name=price_fen,json=priceFen,proto3" json:"price_fen,omitempty"`
	Stock         int64                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminProduct) Reset() {
	*x = AdminProduct{}
	mi := &file_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProduct) ProtoMessage() {}

func (x *AdminProduct) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminProduct.ProtoReflect.Descriptor instead.
func (*AdminProduct) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *AdminProduct) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminProduct) GetPriceFen() int64 {
	if x != nil {
		return x.PriceFen
	}
	return 0
}

func (x *AdminProduct) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AdminProduct) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*AdminProduct        `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReply) Reset() {
	*x = ListProductsReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReply) ProtoMessage() {}

func (x *ListProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReply.ProtoReflect.Descriptor instead.
func (*ListProductsReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ListProductsReply) GetProducts() []*AdminProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PriceFen      int64                  `protobuf:"varint,2,opt,name=price_fen,json=priceFen,proto3" json:"price_fen,omitempty"`
	Stock         int64                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetPriceFen() int64 {
	if x != nil {
		return x.PriceFen
	}
	return 0
}

func (x *UpdateProductRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateProductRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *AdminProduct          `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReply) Reset() {
	*x = UpdateProductReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReply) ProtoMessage() {}

func (x *UpdateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReply.ProtoReflect.Descriptor instead.
func (*UpdateProductReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateProductReply) GetProduct() *AdminProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListLedgerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerRequest) Reset() {
	*x = ListLedgerRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerRequest) ProtoMessage() {}

func (x *ListLedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerRequest.ProtoReflect.Descriptor instead.
func (*ListLedgerRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *ListLedgerRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLedgerRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLedgerRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListLedgerRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type LedgerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountFen     int64                  `protobuf:"varint,3,opt,name=amount_fen,json=amountFen,proto3" json:"amount_fen,omitempty"`
	BalanceFen    int64                  `protobuf:"varint,4,opt,name=balance_fen,json=balanceFen,proto3" json:"balance_fen,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	RefType       string                 `protobuf:"bytes,6,opt,name=ref_type,json=refType,proto3" json:"ref_type,omitempty"`
	RefId         int64                  `protobuf:"varint,7,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *LedgerEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LedgerEntry) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LedgerEntry) GetAmountFen() int64 {
	if x != nil {
		return x.AmountFen
	}
	return 0
}

func (x *LedgerEntry) GetBalanceFen() int64 {
	if x != nil {
		return x.BalanceFen
	}
	return 0
}

func (x *LedgerEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LedgerEntry) GetRefType() string {
	if x != nil {
		return x.RefType
	}
	return ""
}

func (x *LedgerEntry) GetRefId() int64 {
	if x != nil {
		return x.RefId
	}
	return 0
}

func (x *LedgerEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListLedgerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LedgerEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerReply) Reset() {
	*x = ListLedgerReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerReply) ProtoMessage() {}

func (x *ListLedgerReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerReply.ProtoReflect.Descriptor instead.
func (*ListLedgerReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *ListLedgerReply) GetEntries() []*LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListLedgerReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ForcePairSettleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForcePairSettleRequest) Reset() {
	*x = ForcePairSettleRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForcePairSettleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForcePairSettleRequest) ProtoMessage() {}

func (x *ForcePairSettleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForcePairSettleRequest.ProtoReflect.Descriptor instead.
func (*ForcePairSettleRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

type ForcePairSettleReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LastPairSettleDate string                 `protobuf:"bytes,1,opt,name=last_pair_settle_date,json=lastPairSettleDate,proto3" json:"last_pair_settle_date,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ForcePairSettleReply) Reset() {
	*x = ForcePairSettleReply{}
	mi := &file_admin_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForcePairSettleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForcePairSettleReply) ProtoMessage() {}

func (x *ForcePairSettleReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForcePairSettleReply.ProtoReflect.Descriptor instead.
func (*ForcePairSettleReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *ForcePairSettleReply) GetLastPairSettleDate() string {
	if x != nil {
		return x.LastPairSettleDate
	}
	return ""
}

var File_admin_v1_admin_proto protoreflect.FileDescriptor

const file_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x14admin/v1/admin.proto\x12\fapi.admin.v1\x1a\x1cgoogle/api/annotations.proto\"\x11\n" +
	"\x0fGetStatsRequest\"\x87\x02\n" +
	"\rGetStatsReply\x12\x1d\n" +
	"\n" +
	"user_count\x18\x01 \x01(\x03R\tuserCount\x12$\n" +
	"\x0epaid_order_fen\x18\x02 \x01(\x03R\fpaidOrderFen\x12*\n" +
	"\x11direct_reward_fen\x18\x03 \x01(\x03R\x0fdirectRewardFen\x12&\n" +
	"\x0fpair_reward_fen\x18\x04 \x01(\x03R\rpairRewardFen\x12*\n" +
	"\x11manage_reward_fen\x18\x05 \x01(\x03R\x0fmanageRewardFen\x121\n" +
	"\x15last_pair_settle_date\x18\x06 \x01(\tR\x12lastPairSettleDate\"C\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xd0\x02\n" +
	"\tAdminUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1f\n" +
	"\vinvite_code\x18\x04 \x01(\tR\n" +
	"inviteCode\x12\x1d\n" +
	"\n" +
	"inviter_id\x18\x05 \x01(\x03R\tinviterId\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04side\x18\a \x01(\tR\x04side\x12\x19\n" +
	"\bperf_fen\x18\b \x01(\x03R\aperfFen\x12(\n" +
	"\x10settled_pair_fen\x18\t \x01(\x03R\x0esettledPairFen\x12\x1f\n" +
	"\vbalance_fen\x18\n" +
	" \x01(\x03R\n" +
	"balanceFen\x12\x19\n" +
	"\bis_admin\x18\v \x01(\bR\aisAdmin\"U\n" +
	"\x0eListUsersReply\x12-\n" +
	"\x05users\x18\x01 \x03(\v2\x17.api.admin.v1.AdminUserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"u\n" +
	"\vTrackMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1f\n" +
	"\vinvite_code\x18\x03 \x01(\tR\n" +
	"inviteCode\x12\x19\n" +
	"\bperf_fen\x18\x04 \x01(\x03R\aperfFen\"\xbe\x03\n" +
	"\fGetUserReply\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.api.admin.v1.AdminUserR\x04user\x12\"\n" +
	"\rleft_perf_fen\x18\x02 \x01(\x03R\vleftPerfFen\x12$\n" +
	"\x0eright_perf_fen\x18\x03 \x01(\x03R\frightPerfFen\x12$\n" +
	"\x0eavail_left_fen\x18\x04 \x01(\x03R\favailLeftFen\x12&\n" +
	"\x0favail_right_fen\x18\x05 \x01(\x03R\ravailRightFen\x12 \n" +
	"\fpair_vol_fen\x18\x06 \x01(\x03R\n" +
	"pairVolFen\x12 \n" +
	"\fpair_cap_fen\x18\a \x01(\x03R\n" +
	"pairCapFen\x12'\n" +
	"\x10est_pair_pay_fen\x18\b \x01(\x03R\restPairPayFen\x12<\n" +
	"\fleft_members\x18\t \x03(\v2\x19.api.admin.v1.TrackMemberR\vleftMembers\x12>\n" +
	"\rright_members\x18\n" +
	" \x03(\v2\x19.api.admin.v1.TrackMemberR\frightMembers\"\x15\n" +
	"\x13ListProductsRequest\"}\n" +
	"\fAdminProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tprice_fen\x18\x03 \x01(\x03R\bpriceFen\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x03R\x05stock\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"K\n" +
	"\x11ListProductsReply\x126\n" +
	"\bproducts\x18\x01 \x03(\v2\x1a.api.admin.v1.AdminProductR\bproducts\"q\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tprice_fen\x18\x02 \x01(\x03R\bpriceFen\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x03R\x05stock\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"J\n" +
	"\x12UpdateProductReply\x124\n" +
	"\aproduct\x18\x01 \x01(\v2\x1a.api.admin.v1.AdminProductR\aproduct\"q\n" +
	"\x11ListLedgerRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\xdb\x01\n" +
	"\vLedgerEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"amount_fen\x18\x03 \x01(\x03R\tamountFen\x12\x1f\n" +
	"\vbalance_fen\x18\x04 \x01(\x03R\n" +
	"balanceFen\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x19\n" +
	"\bref_type\x18\x06 \x01(\tR\arefType\x12\x15\n" +
	"\x06ref_id\x18\a \x01(\x03R\x05refId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"\\\n" +
	"\x0fListLedgerReply\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.api.admin.v1.LedgerEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x18\n" +
	"\x16ForcePairSettleRequest\"I\n" +
	"\x14ForcePairSettleReply\x121\n" +
	"\x15last_pair_settle_date\x18\x01 \x01(\tR\x12lastPairSettleDate2\x88\x06\n" +
	"\fAdminService\x12_\n" +
	"\bGetStats\x12\x1d.api.admin.v1.GetStatsRequest\x1a\x1b.api.admin.v1.GetStatsReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/admin/stats\x12b\n" +
	"\tListUsers\x12\x1e.api.admin.v1.ListUsersRequest\x1a\x1c.api.admin.v1.ListUsersReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/admin/users\x12a\n" +
	"\aGetUser\x12\x1c.api.admin.v1.GetUserRequest\x1a\x1a.api.admin.v1.GetUserReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/admin/users/{id}\x12n\n" +
	"\fListProducts\x12!.api.admin.v1.ListProductsRequest\x1a\x1f.api.admin.v1.ListProductsReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/admin/products\x12y\n" +
	"\rUpdateProduct\x12\".api.admin.v1.UpdateProductRequest\x1a .api.admin.v1.UpdateProductReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/v1/admin/products/{id}\x12f\n" +
	"\n" +
	"ListLedger\x12\x1f.api.admin.v1.ListLedgerRequest\x1a\x1d.api.admin.v1.ListLedgerReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/admin/ledger\x12}\n" +
	"\x0fForcePairSettle\x12$.api.admin.v1.ForcePairSettleRequest\x1a\".api.admin.v1.ForcePairSettleReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/admin/pair-settleB\x16Z\x14mall/api/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_admin_proto_rawDescOnce sync.Once
	file_admin_v1_admin_proto_rawDescData []byte
)

func file_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)))
	})
	return file_admin_v1_admin_proto_rawDescData
}

var file_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_admin_v1_admin_proto_goTypes = []any{
	(*GetStatsRequest)(nil),        // 0: api.admin.v1.GetStatsRequest
	(*GetStatsReply)(nil),          // 1: api.admin.v1.GetStatsReply
	(*ListUsersRequest)(nil),       // 2: api.admin.v1.ListUsersRequest
	(*AdminUser)(nil),              // 3: api.admin.v1.AdminUser
	(*ListUsersReply)(nil),         // 4: api.admin.v1.ListUsersReply
	(*GetUserRequest)(nil),         // 5: api.admin.v1.GetUserRequest
	(*TrackMember)(nil),            // 6: api.admin.v1.TrackMember
	(*GetUserReply)(nil),           // 7: api.admin.v1.GetUserReply
	(*ListProductsRequest)(nil),    // 8: api.admin.v1.ListProductsRequest
	(*AdminProduct)(nil),           // 9: api.admin.v1.AdminProduct
	(*ListProductsReply)(nil),      // 10: api.admin.v1.ListProductsReply
	(*UpdateProductRequest)(nil),   // 11: api.admin.v1.UpdateProductRequest
	(*UpdateProductReply)(nil),     // 12: api.admin.v1.UpdateProductReply
	(*ListLedgerRequest)(nil),      // 13: api.admin.v1.ListLedgerRequest
	(*LedgerEntry)(nil),            // 14: api.admin.v1.LedgerEntry
	(*ListLedgerReply)(nil),        // 15: api.admin.v1.ListLedgerReply
	(*ForcePairSettleRequest)(nil), // 16: api.admin.v1.ForcePairSettleRequest
	(*ForcePairSettleReply)(nil),   // 17: api.admin.v1.ForcePairSettleReply
}
var file_admin_v1_admin_proto_depIdxs = []int32{
	3,  // 0: api.admin.v1.ListUsersReply.users:type_name -> api.admin.v1.AdminUser
	3,  // 1: api.admin.v1.GetUserReply.user:type_name -> api.admin.v1.AdminUser
	6,  // 2: api.admin.v1.GetUserReply.left_members:type_name -> api.admin.v1.TrackMember
	6,  // 3: api.admin.v1.GetUserReply.right_members:type_name -> api.admin.v1.TrackMember
	9,  // 4: api.admin.v1.ListProductsReply.products:type_name -> api.admin.v1.AdminProduct
	9,  // 5: api.admin.v1.UpdateProductReply.product:type_name -> api.admin.v1.AdminProduct
	14, // 6: api.admin.v1.ListLedgerReply.entries:type_name -> api.admin.v1.LedgerEntry
	0,  // 7: api.admin.v1.AdminService.GetStats:input_type -> api.admin.v1.GetStatsRequest
	2,  // 8: api.admin.v1.AdminService.ListUsers:input_type -> api.admin.v1.ListUsersRequest
	5,  // 9: api.admin.v1.AdminService.GetUser:input_type -> api.admin.v1.GetUserRequest
	8,  // 10: api.admin.v1.AdminService.ListProducts:input_type -> api.admin.v1.ListProductsRequest
	11, // 11: api.admin.v1.AdminService.UpdateProduct:input_type -> api.admin.v1.UpdateProductRequest
	13, // 12: api.admin.v1.AdminService.ListLedger:input_type -> api.admin.v1.ListLedgerRequest
	16, // 13: api.admin.v1.AdminService.ForcePairSettle:input_type -> api.admin.v1.ForcePairSettleRequest
	1,  // 14: api.admin.v1.AdminService.GetStats:output_type -> api.admin.v1.GetStatsReply
	4,  // 15: api.admin.v1.AdminService.ListUsers:output_type -> api.admin.v1.ListUsersReply
	7,  // 16: api.admin.v1.AdminService.GetUser:output_type -> api.admin.v1.GetUserReply
	10, // 17: api.admin.v1.AdminService.ListProducts:output_type -> api.admin.v1.ListProductsReply
	12, // 18: api.admin.v1.AdminService.UpdateProduct:output_type -> api.admin.v1.UpdateProductReply
	15, // 19: api.admin.v1.AdminService.ListLedger:output_type -> api.admin.v1.ListLedgerReply
	17, // 20: api.admin.v1.AdminService.ForcePairSettle:output_type -> api.admin.v1.ForcePairSettleReply
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_admin_v1_admin_proto_init() }
func file_admin_v1_admin_proto_init() {
	if File_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_admin_v1_admin_proto = out.File
	file_admin_v1_admin_proto_goTypes = nil
	file_admin_v1_admin_proto_depIdxs = nil
}
