package biz

import (
	kerrors "github.com/go-kratos/kratos/v2/errors"
)

var (
	ErrForbidden           = kerrors.Forbidden("FORBIDDEN", "需要管理员权限")
	ErrUnauthorized        = kerrors.Unauthorized("UNAUTHORIZED", "请先登录")
	ErrInvalidToken        = kerrors.Unauthorized("UNAUTHORIZED", "无效的登录凭证")
	ErrInvalidArgument     = kerrors.BadRequest("INVALID_ARGUMENT", "请求参数无效")
	ErrUserNotExist        = kerrors.NotFound("USER_NOT_FOUND", "用户不存在")
	ErrProductNotFound     = kerrors.NotFound("PRODUCT_NOT_FOUND", "商品不存在")
	ErrInsufficientStock   = kerrors.BadRequest("INSUFFICIENT_STOCK", "库存不足")
	ErrInsufficientBalance = kerrors.BadRequest("INSUFFICIENT_BALANCE", "余额不足")
	ErrWithdrawTooSmall    = kerrors.BadRequest("WITHDRAW_TOO_SMALL", "提现金额不能小于最小提现数量")
	ErrOrderNotFound       = kerrors.NotFound("ORDER_NOT_FOUND", "订单不存在")
	ErrOrderNotCancellable = kerrors.BadRequest("ORDER_NOT_CANCELLABLE", "认购后不可自行取消")
	ErrInviteAlreadyBound  = kerrors.BadRequest("INVITE_ALREADY_BOUND", "已绑定邀请人，不能更改")
	ErrInviteInvalid       = kerrors.BadRequest("INVITE_INVALID", "邀请码无效")
	ErrInviteSelf          = kerrors.BadRequest("INVITE_SELF", "不能邀请自己")
	ErrUserLocked          = kerrors.Forbidden("USER_LOCKED", "用户已锁定")
	ErrWalletTaken         = kerrors.BadRequest("WALLET_TAKEN", "该钱包地址已被占用")
	ErrAdminProtected      = kerrors.Forbidden("ADMIN_PROTECTED", "不能锁定管理员")
	ErrReleaseDays         = kerrors.BadRequest("RELEASE_DAYS", "请选择释放天数")
	ErrPackageName         = kerrors.BadRequest("PACKAGE_NAME", "请填写名称")
	ErrPackageDesc         = kerrors.BadRequest("PACKAGE_DESC", "请填写描述")
	ErrPackageAmount       = kerrors.BadRequest("PACKAGE_AMOUNT", "金额错误")
	ErrPackageAmountExists = kerrors.BadRequest("PACKAGE_AMOUNT_EXISTS", "金额已存在")
	ErrImageRequired       = kerrors.BadRequest("IMAGE_REQUIRED", "请上传图片")
	ErrImageType           = kerrors.BadRequest("IMAGE_TYPE", "图片格式不支持")
	ErrImageTooLarge       = kerrors.BadRequest("IMAGE_TOO_LARGE", "图片不能超过5MB")
	ErrImageUpload         = kerrors.BadRequest("IMAGE_UPLOAD", "图片上传失败")
	ErrCartEmpty           = kerrors.BadRequest("CART_EMPTY", "请选择认购产品")
	ErrCartMixedDays       = kerrors.BadRequest("CART_MIXED_DAYS", "请选择同一释放天数")
	ErrRechargeTxRequired  = kerrors.BadRequest("RECHARGE_TX_REQUIRED", "请提交链上交易哈希")
	ErrRechargeTxInvalid   = kerrors.BadRequest("RECHARGE_TX_INVALID", "链上交易无效")
	ErrRechargeTxUsed      = kerrors.BadRequest("RECHARGE_TX_USED", "该交易已入账")
	ErrRechargeAmount      = kerrors.BadRequest("RECHARGE_AMOUNT", "充值金额与链上不一致")
	ErrRechargePayer       = kerrors.BadRequest("RECHARGE_PAYER", "充值钱包与登录钱包不一致")
	ErrWithdrawHotWallet   = kerrors.BadRequest("WITHDRAW_HOT_WALLET", "未配置提现热钱包")
	ErrWithdrawChain       = kerrors.BadRequest("WITHDRAW_CHAIN", "链上转账失败，请稍后重试")
)
